In [ ]:
import numpy as np
from scipy.special import expit

s = 100
z = np.random.normal(size=s)
y = np.random.chisquare(df=3, size=s)
params = {'a': 1.0, 'b': 0.5, 'c': 0.8}

def construct_p(z, y, params):
    a, b, c = params['a'], params['b'], params['c']
    m = len(z)
    p = np.zeros((m, m))
    for i in range(m):
        for j in range(m):
            eta = a * (z[i] - z[j]) + b * (y[i] - y[j]) + c * (z[i]*y[j] - z[j]*y[i])
            p[i, j] = expit(eta)
    return p

def sample_X_from_p(p, lam = 1):
    m = p.shape[0]
    # initialiser
    X = np.zeros((m, m), dtype=int)
    # øvre trekant (uten diagonal)
    iu = np.triu_indices(m, k=1)
    # n_ij kun for observerte dyader (øverste trekant)
    n = np.random.poisson(lam=lam, size=len(iu[0]))
    # trekk kun én vei
    X[iu] = np.random.binomial(n, p[iu])
    # speil deterministisk
    X[(iu[1], iu[0])] = n - X[iu]
    np.fill_diagonal(X, 0)
    return X, n
p = construct_p(z, y, params)
X, n = sample_X_from_p(p)
print(X)
print(len(n))

[[0 0 0 ... 0 0 1]
 [0 0 0 ... 1 0 2]
 [2 1 0 ... 0 0 3]
 ...
 [2 1 2 ... 0 2 2]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
4950


In [7]:
import numpy as np

a= np.array([1,2])
print(np.atan2(a[1], a[0])/(2*np.pi)*360)

63.43494882292201
